version: "2"
run:
  go: "1.22"
linters:
  default: none
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gomodguard
    - govet
    - importas
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 200
    gocyclo:
      min-complexity: 20
    gomodguard:
      allowed:
        modules:
          - github.com/nextmv-io/sdk
          - gonum.org/v1/gonum
    lll:
      line-length: 120
    tagliatelle:
      case:
        rules:
          json: snake
        use-field-name: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - gocyclo
        path: .*_test\.go
      - linters:
          - gocyclo
        path: model_expression_time_dependent_test\.go
      - linters:
          - gocyclo
        path: solution_construction_cluster\.go
      - linters:
          - gocyclo
        path: model_constraint_no_mix_test\.go
      - linters:
          - gocyclo
          - nestif
        path: check/check\.go
      - linters:
          - gocyclo
        path: solution_move\.go
      - linters:
          - gocyclo
        path: solution_move_stops\.go
      - linters:
          - gocyclo
        path: solve_solver_parallel\.go
      - linters:
          - gocyclo
        path: solution\.go
      - linters:
          - staticcheck
        path: solution_vehicle\.go
        text: SA6002
      - linters:
          - gocyclo
        path: model_plan_unit_test\.go
      - linters:
          - gocyclo
        path: model_plan_units_unit_test\.go
      - linters:
          - gocyclo
        path: model_plan_stops_unit_test\.go
      - linters:
          - gocyclo
        path: model_constraint_maximum_test\.go
      - linters:
          - nestif
        path: model\.go
      - linters:
          - gocyclo
        path: model_test\.go
      - linters:
          - nestif
        path: solution_stop_generator\.go
      - linters:
          - nestif
        path: model_factory\.go
      - linters:
          - govet
        path: solver\.go
      - linters:
          - govet
        path: solver_parallel.go
      - linters:
          - lll
        path: solution_observer\.go
      - linters:
          - gocyclo
        path: factory/validate\.go
      - linters:
          - gocyclo
          - nestif
        path: factory/construction\.go
      - linters:
          - nestif
        path: factory/constraint_no_mix\.go
      - linters:
          - gocyclo
          - nestif
        path: factory/plan_units\.go
      - linters:
          - nestif
        path: factory/format\.go
      - linters:
          - dogsled
        path: model_objective_vehicles_duration\.go
      - linters:
          - gocritic
        path: factory/validate\.go
      - linters:
          - gocritic
        path: factory/plan_units\.go
        text: ifElseChain
      - linters:
          - nestif
        path: solution_vehicle\.go
      - linters:
          - unparam
        path: model_constraint\.go
      - linters:
          - unparam
        path: solution_stop_generator\.go
      - linters:
          - lll
        path: solver\.go
      - linters:
          - lll
        path: solve_solver_parallel\.go
      - linters:
          - lll
        path: solve_solver\.go
      - linters:
          - lll
        path: check/options\.go
      - linters:
          - lll
        path: schema
      - linters:
          - lll
        path: model\.go
      - linters:
          - gocyclo
        path: model\.go
      - linters:
          - lll
        path: factory/model\.go
      - linters:
          - lll
        path: factory/construction\.go
      - linters:
          - gocyclo
        path: schema/fleet_defaults\.go
      - linters:
          - staticcheck
        path: schema/router\.go
      - linters:
          - govet
        path: schema/input\.go
        text: structtag
      - linters:
          - goconst
        path: precedence\.go
      - linters:
          - nestif
        path: model_directed_acyclic_graph\.go
      - linters:
          - nestif
        path: solution_move_stops_generator\.go
      - linters:
          - nestif
        path: solution_sequence_generator\.go
      - linters:
          - gocyclo
        path: factory/vehicles\.go
      - linters:
          - tagliatelle
        path: schema/input\.go
      - linters:
          - revive
        text: avoid meaningless package names
      - linters:
          - contextcheck
        path: check/format\.go
      - linters:
          - nestif
        path: factory/validate\.go
      - linters:
          - revive
        path: common/.*\.go # we do not want to break users to address the "common" package naming
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
