name: auto benchmark
on:
  workflow_dispatch:
  push:
    branches:
      - "develop"

permissions:
  contents: read

env:
  GO_VERSION: 1.26
  PYTHON_VERSION: 3.12

jobs:
  auto-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.9.29"
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install the project
        run: uv sync --locked --group benchmark

      - name: run acceptance test
        env:
          BENCHMARK_ACCOUNT_ID: ${{ vars.BENCHMARK_ACCOUNT_ID }}
          BENCHMARK_API_KEY_PROD: ${{ secrets.BENCHMARK_API_KEY_PROD }}
          SLACK_URL_DEV_SCIENCE: ${{ secrets.SLACK_URL_DEV_SCIENCE }}
        run: |
          export BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          uv run .nextmv/benchmark.py
