name: auto benchmark
on: [push]

env:
  GO_VERSION: 1.23
  PYTHON_VERSION: 3.12

jobs:
  auto-benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .nextmv/benchmark.requirements.txt

      - name: run acceptance test
        run: |
          export BRANCH_NAME=$(echo $GITHUB_REF | awk -F'/' '{print $3}')
          export BENCHMARK_API_KEY_PROD=${{ secrets.BENCHMARK_API_KEY_PROD }}
          export SLACK_URL_DEV_SCIENCE=${{ secrets.SLACK_URL_DEV_SCIENCE }}
          export BENCHMARK_ACCOUNT_ID=${{ env.BENCHMARK_ACCOUNT_ID }}
          python .nextmv/benchmark.py
